### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by LocalSmail**
double click detection

### CODE REVIEW

**Comment by KDot227** [comment]
When obfuscated it already has double click check. On top of this it gets started from a bat file so that wouldn't work. Get your money up not your funny up.

**Comment by KDot227** [comment]
Kids man

**Comment by LocalSmail** [comment]
jit

**Comment by LocalSmail** [comment]
this is for the python file. the double click detection doesnt work for the py file

**Comment by LocalSmail** [comment]
goofy ahh

**Pull request closed without merging**
