### PR TITLE
Code Refactor

### PR DESCRIPTION
**Pull request by Chainski**
```
$ErrorActionPreference = 'SilentlyContinue' # Ignore all warnings
$ProgressPreference = 'SilentlyContinue' # Hide all Progresses
```
- [x] Added the variables above start of the code instead of every line, hence reducing code size and improving performance.
- [x] Improved Anti-Analysis Checklist
- [x] Updated README

### CODE REVIEW

**Comment by KDot227** [comment]
@Chainski U gotta fix some of your spacings bro

**Comment by KDot227** [comment]
The indents are so inconsistent 😭

**Comment by Chainski** [comment]
> The indents are so inconsistent 😭

I fixed them , you can merge the request now.

BTW the ANTI-VM thing can be server-sided to reduce code size I realized that you removed it a few times , Is there an issue why you removed it ?

**Comment by KDot227** [comment]
@Chainski do u mind joining the server cause I gotta help u fix ur editor or sum. Everything u add is good asf but there is just hella random stuff that's messed up.

**Pull request merged**
