### PR TITLE
Updates 

### PR DESCRIPTION
**Pull request by Chainski**
- [x] Updated README
- [x] Fixed Mutex 
- [x] Fixed Errors
- [x] Readded Ditigal Signature

### CODE REVIEW

**Comment by KDot227** [comment]
@Chainski can u do with the current version?

**Comment by Chainski** [comment]
> @Chainski can u do with the current version?

Had to refactor the codebase as none of the ```session stealers``` worked with your branch :( 
***Issue*** : https://github.com/KDot227/Powershell-Token-Grabber/issues/105 may actually be true but since my [main](https://github.com/Chainski/PowerShell-Token-Grabber) branch is updated you can now merge & this issue can be addressed and closed asap.

**Comment by KDot227** [comment]
> > @Chainski can u do with the current version?
> 
> 
> 
> Had to refactor the codebase as none of the ```session stealers``` worked with your branch :( 
> 
> ***Issue*** : https://github.com/KDot227/Powershell-Token-Grabber/issues/105 may actually be true but since my [main](https://github.com/Chainski/PowerShell-Token-Grabber) branch is updated you can now merge & this issue can be addressed and closed asap.

I'll merge but after this we gotta stop the function nesting 😭😭😭😭😭

**Comment by KDot227** [comment]
I'm pretty sure ik why the session stealers aren't working too

**Pull request merged**
