### PR TITLE
Added more features and improvements

### PR DESCRIPTION
**Pull request by Chainski**
See the [README](https://github.com/Chainski/Powershell-Token-Grabber/blob/main/README.md) for more details
- More features are underway.

### CODE REVIEW

**Comment by KDot227** [comment]
lmao love it @Chainski did you test to see if it works with invoke-obfuscation

**Comment by KDot227** [comment]
Also i'm almost done with decrypting tokens in powershell and i'll add that soon too

**Comment by Chainski** [comment]
> lmao love it @Chainski did you test to see if it works with invoke-obfuscation

- Yes it works but takes quite a while due to the heavily-obfuscated code.

**Comment by KDot227** [comment]
@Chainski tomorrow I'll change all the invoke-webrequest stuff to other transfer for speed

**Pull request merged**
