### PR TITLE
Minor Fix

### PR DESCRIPTION
**Pull request by Chainski**
- [x] Fixed the collection of ```Browser Data```  
```resolved``` https://github.com/KDot227/Powershell-Token-Grabber/issues/105#issuecomment-1595846020

### CODE REVIEW

**Comment by xXenvy** [comment]
This pull request does not fix it. It still doesn't work.

**Comment by KDot227** [comment]
> This pull request does not fix it. It still doesn't work.

Can you send an error so we can help?

**Comment by KDot227** [comment]
I can't read your mind

**Comment by Chainski** [comment]
This pull request actually fixed the error for me, the problem you may have is where the ```get-screenshot``` C# code may get flagged by  Windows Defender so the```main.ps1``` gets killed at runtime, so I suggest you obfuscate the script and patch ```amsi``` or disable Windows Defender, otherwise everything else should be fine.

image

**Pull request merged**
