### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Chainski**
- [x] Updated README
- [x] Added Viber Session Stealer
- [x] Added WhatsApp Session Stealer
- [x] Updated GrabFiles Checklist

### CODE REVIEW

**Comment by KDot227** [comment]
@Chainski for Whatsapp try and use regex or something instead of just putting the path

5319275A.WhatsAppDesktop_cv1g1gvanyjgm

since I feel like thats almost fasho user specific or version specific

**Comment by KDot227** [comment]
then ill merge

**Comment by Chainski** [comment]
> then ill merge

I made a few changes could you please download ```WhatsApp``` on your pc and test it , I think it should be effective by now...

**Comment by KDot227** [comment]
Shi it prolly works I trust u

**Comment by Resisst** [comment]
> @Chainski for Whatsapp try and use regex or something instead of just putting the path
> 
> 5319275A.WhatsAppDesktop_cv1g1gvanyjgm
> 
> since I feel like thats almost fasho user specific or version specific

It's not I don't think, thats just the name of the package on Microsoft Store but I could be wrong.

**Comment by xpierroz** [comment]
> > @Chainski for Whatsapp try and use regex or something instead of just putting the path
> > 5319275A.WhatsAppDesktop_cv1g1gvanyjgm
> > since I feel like thats almost fasho user specific or version specific
> 
> It's not I don't think, thats just the name of the package on Microsoft Store but I could be wrong.

yes I have the same package name, it's not user-specific

**Pull request merged**
