### PR TITLE
Minor Fix and New Feature

### PR DESCRIPTION
**Pull request by Chainski**
- [x] Updated README
- [x] Added Minecraft Session Stealer
- [x] Fixed an error with session files

### CODE REVIEW

**Comment by KDot227** [comment]
@Chainski does the auto update work for u

**Comment by KDot227** [comment]
I also plan on making a debug mode so it won't auto update and also do less obf, etc

**Comment by Chainski** [comment]
> @Chainski does the auto update work for u

Yes it works, you could also add an option in the gui builder that does the autoupdate check.

**Comment by KDot227** [comment]
> > @Chainski does the auto update work for u
> 
> 
> 
> Yes it works, you could also add an option in the gui builder that does the autoupdate check.

Bet I'll try

**Pull request merged**
